name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Geode SDK
        uses: geode-sdk/setup-geode@v1
        with:
          version: '4.9.0' # change if you want a different SDK version

      - name: Build mod
        run: geode build

      - name: Upload .geode
        uses: actions/upload-artifact@v3
        with:
          name: geode-mod
          path: build/*.geode
